version: '3'

services:

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./mongoData:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=chocu
    networks:
      - mainNet
  
  laravel:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        uid: 1000  # Valor de ejemplo para el ID de usuario
        user: chocu  # Valor de ejemplo para el nombre de usuario
    ports:
      - "8000:8000"  # Puerto para el servidor de desarrollo de Laravel
      - "6001:6001"  # Puerto para los websockets
    volumes:
      - ./RemCat:/var/www/html
      - ./php:/usr/local/etc/php
    command: > # Arranca laravel y los websockets al iniciar la app
      sh -c "php /var/www/html/artisan serve --host 0.0.0.0 --port 8000 & php /var/www/html/artisan websockets:serve"
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
    networks:
      - mainNet
  mongo-cli:
    image: mongo-express:1.0.2-20
    ports:
      - "8081:8081"
    restart: always
    environment: 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=chocu
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=chocu
      - ME_CONFIG_SITE_BASEURL=/mongoadmin
      # Uncomment this line below when you use reverse proxy and want to reach the UI on specific path
      #- ROOT_URL=https://example.com/nosqlclient
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
    networks:
      - mainNet

volumes:
   mongoData:
    driver: local
   clientdb:
    driver: local

networks:
  mainNet:
    name: mainNet
    driver: bridge
